#!/usr/bin/env python3
"""Regenerate docs/registry/index.md — the browsable catalog of registry entries.

Renders every registry/agents/*.yaml and registry/skills/*.yaml as a card on the
docs site, so registered agents and skills are discoverable without reading YAML.

Deterministic (entries sorted by id) so CI can assert the committed page is fresh
via `git diff --exit-code`. Run after adding/editing an entry:

    python scripts/build_registry_page.py
"""
from __future__ import annotations

import html
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("Missing deps. Run:  pip install pyyaml")

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "registry" / "index.md"

STATUSES = {"active", "pending", "deprecated"}


def _load(kind: str) -> list[dict]:
    d = ROOT / "registry" / kind
    out = []
    if d.exists():
        for f in sorted(d.glob("*.yaml")):
            if f.name.startswith("_"):
                continue
            try:
                data = yaml.safe_load(f.read_text()) or {}
            except yaml.YAMLError as e:
                sys.exit(f"{f.relative_to(ROOT)}: invalid YAML: {e}")
            if isinstance(data, dict) and data.get("id"):
                out.append(data)
    return sorted(out, key=lambda e: e["id"])


def _esc(s: object) -> str:
    return html.escape(str(s or ""), quote=True)


def _status_chip(e: dict) -> str:
    st = e.get("status", "")
    cls = st if st in STATUSES else "unknown"
    return f'<span class="tx-reg-status tx-reg-status--{cls}">{_esc(st) or "unknown"}</span>'


def _domains(e: dict) -> str:
    doms = e.get("domains") or []
    if not doms:
        return ""
    chips = "".join(f'<span class="tx-reg-domain">{_esc(d)}</span>' for d in doms)
    return f'<p class="tx-reg-domains">{chips}</p>'


def _links(pairs: list[tuple[str, str]]) -> str:
    items = [f'<a href="{_esc(url)}">{_esc(label)}</a>' for label, url in pairs if url]
    return f'<p class="tx-reg-links">{" · ".join(items)}</p>' if items else ""


def _agent_card(e: dict) -> str:
    icon = _esc(e.get("icon") or "🤖")
    maint = (e.get("maintainers") or [{}])[0]
    gh = maint.get("github", "")
    sub = e.get("skills") or []
    sub_html = ""
    if sub:
        rows = "".join(
            f"<li><code>{_esc(s.get('id'))}</code> — {_esc(s.get('description'))}</li>"
            for s in sub if isinstance(s, dict)
        )
        sub_html = f'<ul class="tx-reg-sub">{rows}</ul>'
    links = _links([
        (f"@{gh}", f"https://github.com/{gh}" if gh else ""),
        ("homepage", e.get("homepage", "")),
        ("YAML", f"https://github.com/zhenghh04/trinity_hub/blob/main/registry/agents/{e['id']}.yaml"),
    ])
    return f"""<li class="tx-reg-card">
<p class="tx-reg-head"><span class="tx-reg-icon">{icon}</span>
<strong>{_esc(e.get("name", e["id"]))}</strong> {_status_chip(e)}</p>
<p class="tx-reg-meta"><code>@{_esc(e["id"])}</code>
<span class="tx-reg-proto">{_esc(e.get("protocol", ""))}</span>
<span class="tx-reg-owner">{_esc(e.get("owner", ""))}</span></p>
<p>{_esc(e.get("description", ""))}</p>
{sub_html}
{_domains(e)}
{links}
</li>"""


def _skill_card(e: dict) -> str:
    maint = (e.get("maintainers") or [{}])[0]
    gh = maint.get("github", "")
    src = e.get("source") or {}
    trigger = e.get("trigger", "")
    trig_html = f'<p class="tx-reg-trigger">Say: {_esc(trigger)}</p>' if trigger else ""
    io_rows = []
    for label, key in (("Inputs", "inputs"), ("Outputs", "outputs"), ("Needs", "requirements")):
        if e.get(key):
            io_rows.append(f"<li><strong>{label}:</strong> {_esc(e[key])}</li>")
    io_html = f'<ul class="tx-reg-sub">{"".join(io_rows)}</ul>' if io_rows else ""
    links = _links([
        (f"@{gh}", f"https://github.com/{gh}" if gh else ""),
        ("source", src.get("repo", "")),
        ("YAML", f"https://github.com/zhenghh04/trinity_hub/blob/main/registry/skills/{e['id']}.yaml"),
    ])
    return f"""<li class="tx-reg-card">
<p class="tx-reg-head"><span class="tx-reg-icon">🧩</span>
<strong>{_esc(e.get("name", e["id"]))}</strong> {_status_chip(e)}</p>
<p class="tx-reg-meta"><code>{_esc(e["id"])}</code>
<span class="tx-reg-owner">{_esc(e.get("owner", ""))}</span></p>
<p>{_esc(e.get("description", ""))}</p>
{trig_html}
{io_html}
{_domains(e)}
{links}
</li>"""


def main() -> int:
    agents = _load("agents")
    skills = _load("skills")

    parts = [
        "<!-- GENERATED by scripts/build_registry_page.py — do not edit by hand. -->",
        "# Registry catalog",
        "",
        f"**{len(agents)} agent(s)** and **{len(skills)} skill(s)** are registered in "
        "[Trinity Hub](https://github.com/zhenghh04/trinity_hub/tree/main/registry). "
        "Agents run on their maintainers' infrastructure and become `@mention`-able in "
        "Trinity rooms; skills are reusable capabilities any Trinity agent can load.",
        "",
        '!!! tip "Add yours"',
        "    [Register an agent](../register-an-agent.md) or "
        "[contribute a skill](../contribute-a-skill.md) — one YAML file and a pull request.",
        "",
        "## Agents",
        "",
    ]
    if agents:
        parts.append('<div class="grid cards tx-reg-grid"><ul>' +
                     "\n".join(_agent_card(e) for e in agents) + "</ul></div>")
    else:
        parts.append("_No agents registered yet — [be the first](../register-an-agent.md)._")

    parts += ["", "## Skills", ""]
    if skills:
        parts.append('<div class="grid cards tx-reg-grid"><ul>' +
                     "\n".join(_skill_card(e) for e in skills) + "</ul></div>")
    else:
        parts.append("_No skills shared yet — [be the first](../contribute-a-skill.md)._")

    parts += [
        "",
        "## Status legend",
        "",
        "| Status | Meaning |",
        "|---|---|",
        "| `active` | Reachable and usable in Trinity rooms today. |",
        "| `pending` | Registered; endpoint or credentials still being finalized. |",
        "| `deprecated` | Kept for the record; no longer maintained. |",
        "",
    ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(parts))
    print(f"wrote docs/registry/index.md ({len(agents)} agents, {len(skills)} skills)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
