#!/usr/bin/env python3
"""Regenerate registry/INDEX.md — the human-readable catalog of all entries.

Deterministic (entries sorted by id) so CI can assert the committed index is fresh
via `git diff --exit-code`. Run after adding/editing an entry:

    python scripts/build_index.py
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("Missing deps. Run:  pip install pyyaml")

ROOT = Path(__file__).resolve().parent.parent


def _load(kind: str) -> list[dict]:
    d = ROOT / "registry" / kind
    out = []
    if d.exists():
        for f in sorted(d.glob("*.yaml")):
            if f.name.startswith("_"):
                continue
            try:
                data = yaml.safe_load(f.read_text()) or {}
            except yaml.YAMLError as e:
                sys.exit(f"{f.relative_to(ROOT)}: invalid YAML: {e}")
            if isinstance(data, dict) and data.get("id"):
                out.append(data)
    return sorted(out, key=lambda e: e["id"])


def _maint(e: dict) -> str:
    m = (e.get("maintainers") or [{}])[0]
    return m.get("github", "—")


def main() -> int:
    agents = _load("agents")
    skills = _load("skills")

    lines = [
        "<!-- GENERATED by scripts/build_index.py — do not edit by hand. -->",
        "# Trinity Hub — Registry Index",
        "",
        f"**{len(agents)} agent(s)** · **{len(skills)} skill(s)**",
        "",
        "## Agents",
        "",
        "| id | name | domains | protocol | status | maintainer |",
        "|---|---|---|---|---|---|",
    ]
    for e in agents:
        lines.append("| `{id}` | {name} | {domains} | {protocol} | {status} | {m} |".format(
            id=e["id"], name=e.get("name", ""),
            domains=", ".join(e.get("domains") or []),
            protocol=e.get("protocol", ""), status=e.get("status", ""), m=_maint(e)))
    if not agents:
        lines.append("| _none yet_ | | | | | |")

    lines += ["", "## Skills", "",
              "| id | name | domains | status | source |",
              "|---|---|---|---|---|"]
    for e in skills:
        src = (e.get("source") or {}).get("repo", "")
        lines.append("| `{id}` | {name} | {domains} | {status} | {src} |".format(
            id=e["id"], name=e.get("name", ""),
            domains=", ".join(e.get("domains") or []),
            status=e.get("status", ""), src=src))
    if not skills:
        lines.append("| _none yet_ | | | | |")

    lines += ["",
              "---",
              "Add an agent: [docs/register-an-agent.md](../docs/register-an-agent.md) · "
              "Add a skill: [docs/contribute-a-skill.md](../docs/contribute-a-skill.md)",
              ""]

    (ROOT / "registry" / "INDEX.md").write_text("\n".join(lines))
    print(f"wrote registry/INDEX.md ({len(agents)} agents, {len(skills)} skills)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
